name: Cypress Cloud

on:
  workflow_dispatch:
    inputs:
      spec:
        description: Run by cypress command line
        default: cypress/e2e/*

jobs:
  cypress-e2e-electron:
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-22.14.0-chrome-133.0.6943.53-1-ff-135.0-edge-133.0.3065.59-1
      options: --user 1001
    steps:
        - name: Get code
          uses: actions/checkout@v4.2.2

        - name: Cypress run
          uses: cypress-io/github-action@v6.5.0      
          with:
            install-command: npm install
            browser: electron
            record: true
            group: UI Electron
            spec: ${{ github.event.inputs.spec }}
          env:
           CYPRESS_RECORD_KEY: 42c8dc28-15e5-4e90-9443-5fde19781ce8
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  cypress-e2e-chrome:
    needs: cypress-e2e-electron
    runs-on: ubuntu-latest
    container:
      image: cypress/browsers:node-22.14.0-chrome-133.0.6943.53-1-ff-135.0-edge-133.0.3065.59-1
      options: --user 1001
    steps:
        - name: Get code
          uses: actions/checkout@v4.2.2

        - name: Cypress run
          uses: cypress-io/github-action@v6.5.0      
          with:
            install-command: npm install
            browser: chrome
            record: true
            group: UI Chrome
            spec: ${{ github.event.inputs.spec }}
          env:
           CYPRESS_RECORD_KEY: 42c8dc28-15e5-4e90-9443-5fde19781ce8
           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  cypress-e2e-firefox-windows:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4.2.2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Firefox via Chocolatey
        run: choco install firefox -y

      - name: Install dependencies
        run: npm install

      - name: Run Cypress Tests in Firefox
        uses: cypress-io/github-action@v6.5.0
        with:
          browser: firefox
          record: true
          group: "UI Firefox Windows"
          spec: ${{ github.event.inputs.spec }}
        env:
          CYPRESS_RECORD_KEY: ${{ secrets.CYPRESS_RECORD_KEY }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

